apiVersion: v1
kind: Service
metadata:
  name: openmanage-ai
  namespace: openmanage-production
  labels:
    app: openmanage-ai
    env: production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: openmanage-ai
    env: production
